FROM python:3.10-slim-buster

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV PYTHONPATH "${PYTHONPATH}:/app/"

COPY app/client/ ./client/
COPY app/configs/ ./configs/

RUN pip install --no-cache-dir -r /app/client/requirements.txt
RUN rm -rf /root/.cache/pip/*

# CMD is currently set in docker-compose.yml
# CMD ["python", "/app/client/app.py"]